name: 'inspection_app'
description: "Projeto Flutter para o aplicativo Lince, utilizado para inspeções."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  search_cep: ^4.0.2
  camera: ^0.11.1
  permission_handler: ^11.4.0
  connectivity_plus: ^6.1.3
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  file_picker: ^8.1.2
  share_plus: ^11.0.0
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  shared_preferences: ^2.3.2
  brasil_fields: ^1.17.0
  image_picker: ^1.0.8
  path: ^1.9.1
  uuid: ^4.5.1
  json_annotation: ^4.9.0
  intl: ^0.20.2
  crypto: ^3.0.6
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  flutter_lints: ^5.0.0
  cpf_cnpj_validator: ^2.0.0
  speech_to_text: ^7.0.0
  url_launcher: ^6.3.1
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  video_player: ^2.8.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  firebase_messaging: ^15.2.6
  image: ^4.5.4
  qr_flutter: ^4.1.0
  flutter_svg: ^2.1.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.9.0
  build_runner: ^2.4.8

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/splash_screen/
    - assets/icons/
    - .env
    
  # Adicione suas fontes se necessário
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
