// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdc2rReinL8jyW0O2o6pzKLdjw9cazBoI',
    appId: '1:688335169547:web:7ab47b0accbbc78c7dbf0e',
    messagingSenderId: '688335169547',
    projectId: 'inspection-app-2025',
    authDomain: 'inspection-app-2025.firebaseapp.com',
    storageBucket: 'inspection-app-2025.firebasestorage.app',
    measurementId: 'G-KF2Z2YWGF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7PBaF7FSNy_Bm_13fV_VDmxX6yMg4LhY',
    appId: '1:688335169547:android:3784f402404aa53d7dbf0e',
    messagingSenderId: '688335169547',
    projectId: 'inspection-app-2025',
    storageBucket: 'inspection-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ_it8Ochw8zUChB6hg_Oa8Wv92wdeoQY',
    appId: '1:688335169547:ios:0221efd8b34cf96a7dbf0e',
    messagingSenderId: '688335169547',
    projectId: 'inspection-app-2025',
    storageBucket: 'inspection-app-2025.firebasestorage.app',
    iosBundleId: 'com.corp.inspectionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ_it8Ochw8zUChB6hg_Oa8Wv92wdeoQY',
    appId: '1:688335169547:ios:0221efd8b34cf96a7dbf0e',
    messagingSenderId: '688335169547',
    projectId: 'inspection-app-2025',
    storageBucket: 'inspection-app-2025.firebasestorage.app',
    iosBundleId: 'com.corp.inspectionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdc2rReinL8jyW0O2o6pzKLdjw9cazBoI',
    appId: '1:688335169547:web:6d3f216529aab98b7dbf0e',
    messagingSenderId: '688335169547',
    projectId: 'inspection-app-2025',
    authDomain: 'inspection-app-2025.firebaseapp.com',
    storageBucket: 'inspection-app-2025.firebasestorage.app',
    measurementId: 'G-H6N2F6Q7C7',
  );
}
