// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:lince_inspecoes/models/detail.dart';
import 'package:lince_inspecoes/models/inspection.dart';
import 'package:lince_inspecoes/models/item.dart';
import 'package:lince_inspecoes/models/non_conformity.dart';
import 'package:lince_inspecoes/models/offline_media.dart';
import 'package:lince_inspecoes/models/sync_queue.dart';
import 'package:lince_inspecoes/models/template.dart';
import 'package:lince_inspecoes/models/topic.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DetailAdapter());
    registerAdapter(InspectionAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(NonConformityAdapter());
    registerAdapter(OfflineMediaAdapter());
    registerAdapter(SyncQueueAdapter());
    registerAdapter(TemplateAdapter());
    registerAdapter(TopicAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DetailAdapter());
    registerAdapter(InspectionAdapter());
    registerAdapter(ItemAdapter());
    registerAdapter(NonConformityAdapter());
    registerAdapter(OfflineMediaAdapter());
    registerAdapter(SyncQueueAdapter());
    registerAdapter(TemplateAdapter());
    registerAdapter(TopicAdapter());
  }
}
